trigger:
  branches:
    include:
      - main

pool:
  name: 'myagentpool'
  demands:
    - agent.name -equals azDevOpsAgentSelf
    
parameters:
  - name: configuration
    displayName: Configuration
    type: string
    default: 'no'
    values:
      - 'yes'
      - 'no'

steps:
  - checkout: self
    displayName: 'Checkout Repository'

  - script: |
      echo "Building Docker image..."
      docker build -t my-docker-image:latest .
    displayName: 'Build Docker Image'

  - script: |
      if "%configuration%" == "yes" (
        echo "Deleting Docker image..."
        docker rmi my-docker-image:latest || exit 0
      ) else (
        echo "Skipping Docker image deletion."
      )
    displayName: 'Delete Docker Image'
    shell: cmd
